export const UI_TEXTOS = {
  pt: {
    htmlLang: 'pt-BR',
    tituloApp: 'Sistema Solar — Simulador Interativo',
    titulo: 'SISTEMA SOLAR',
    subtitulo: 'Simulador interativo',
    btnEventos: '✦ Eventos',
    btnTamanhos: '⚖ Tamanhos',
    btnQuiz: '◈ Quiz',
    btnVoce: '◍ Você no Espaço',
    btnTour: '▶ Tour guiado',
    escalaDidatica: 'Didática',
    escalaReal: 'Real',
    btnOrbitas: 'Órbitas',
    btnRotulos: 'Rótulos',
    btnVisaoGeral: '⌂ Visão geral',
    explorar: 'Explorar',
    recolherMenu: 'Recolher menu',
    expandirMenu: 'Expandir menu',
    grupoEstrela: 'ESTRELA',
    grupoPlanetas: 'PLANETAS',
    grupoAnoes: 'PLANETAS-ANÕES',
    grupoCinturoes: 'CINTURÕES',
    grupoAsteroides: 'ASTEROIDES',
    grupoCometas: 'COMETAS',
    grupoTelescopios: 'TELESCÓPIOS ESPACIAIS',
    grupoMissoes: 'MISSÕES ESPACIAIS',
    pausado: 'Pausado',
    umDiaPorSegundo: '1 dia/s',
    diasPorSegundo: '{n} dias/s',
    hoje: 'Hoje',
    tituloSlider: 'Velocidade da simulação — esquerda volta no tempo, direita avança',
    chipEstrela: 'ESTRELA',
    chipPlaneta: 'PLANETA',
    chipPlanetaAnao: 'PLANETA-ANÃO',
    chipLuaDe: 'LUA DE {nome}',
    chipLua: 'LUA',
    chipCinturao: 'CINTURÃO',
    chipAsteroide: 'ASTEROIDE',
    chipCometa: 'COMETA',
    chipSonda: 'TELESCÓPIO ESPACIAL',
    planetaAPartirDoSol: '{ordinal} planeta a partir do Sol',
    luaDe: 'Lua de {nome}',
    curiosidades: 'Curiosidades',
    paraSentirEscala: 'Para sentir a escala',
    luas: 'Luas',
    saibaMais: 'Saiba mais (11+)',
    composicao: 'Composição:',
    temperatura: 'Temperatura:',
    missoesExploratorias: 'Missões exploratórias',
    eventosTitulo: 'Eventos',
    jaPassou: 'JÁ PASSOU',
    irParaData: 'Ir para a data',
    semEventos: 'Nenhum evento disponível.',
    tipoEvento_eclipse: 'ECLIPSE',
    tipoEvento_oposicao: 'OPOSIÇÃO',
    tipoEvento_conjuncao: 'CONJUNÇÃO',
    tipoEvento_chuva_meteoros: 'CHUVA DE METEOROS',
    tipoEvento_cometa: 'COMETA',
    tipoEvento_marco: 'MARCO',
    comparadorTitulo: 'Comparador de Tamanhos',
    incluirSol: 'Incluir o Sol',
    paradaDe: 'PARADA {n} DE {m}',
    anterior: '← Anterior',
    proximo: 'Próximo →',
    concluir: 'Concluir',
    sair: 'Sair',
    irParaLancamento: 'Ir para o lançamento',
    seguirNave: '🛰 Seguir a nave',
    toastDica: 'Arraste para girar · Role para dar zoom · Clique em um astro para conhecê-lo',
    credito: 'Texturas: Solar System Scope (CC BY 4.0) · Dados: NASA/JPL',
    seletorIdioma: 'Idioma',
    meses: [
      'janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho',
      'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'
    ],
    mesesCurtos: [
      'jan', 'fev', 'mar', 'abr', 'mai', 'jun',
      'jul', 'ago', 'set', 'out', 'nov', 'dez'
    ],
    proBadge: 'PRO',
    paywallTitulo: 'Explorador Pro',
    paywallSubtitulo: 'Desbloqueie a exploração completa',
    paywallBeneficio1: 'Quiz Espacial completo com medalhas e caça aos astros',
    paywallBeneficio2: 'Todas as 10 missões espaciais com trajetórias reais em 3D',
    paywallBeneficio3: 'Viagem no tempo até eclipses e eventos astronômicos',
    paywallBeneficio4: 'Seu peso, idade e salto em cada planeta',
    paywallPreco: 'R$ 12,90 · compra única',
    paywallComprar: 'Desbloquear agora',
    paywallComprando: 'Processando…',
    paywallRestaurar: 'Restaurar compra',
    paywallSucesso: 'Desbloqueado! Bom passeio pelo cosmos.',
    paywallErro: 'Não foi possível concluir. Tente novamente.',
    paywallRestaurado: 'Compra restaurada!',
    paywallNadaRestaurar: 'Nenhuma compra anterior encontrada.',
    paywallLegal: 'Pagamento de demonstração (mock) — nenhuma cobrança real é feita nesta versão.',
    cadeadoTitulo: 'Recurso Pro — toque para desbloquear'
  },
  en: {
    htmlLang: 'en',
    tituloApp: 'Solar System — Interactive Simulator',
    titulo: 'SOLAR SYSTEM',
    subtitulo: 'Interactive simulator',
    btnEventos: '✦ Events',
    btnTamanhos: '⚖ Sizes',
    btnQuiz: '◈ Quiz',
    btnVoce: '◍ You in Space',
    btnTour: '▶ Guided tour',
    escalaDidatica: 'Didactic',
    escalaReal: 'Real',
    btnOrbitas: 'Orbits',
    btnRotulos: 'Labels',
    btnVisaoGeral: '⌂ Overview',
    explorar: 'Explore',
    recolherMenu: 'Collapse menu',
    expandirMenu: 'Expand menu',
    grupoEstrela: 'STAR',
    grupoPlanetas: 'PLANETS',
    grupoAnoes: 'DWARF PLANETS',
    grupoCinturoes: 'BELTS',
    grupoAsteroides: 'ASTEROIDS',
    grupoCometas: 'COMETS',
    grupoTelescopios: 'SPACE TELESCOPES',
    grupoMissoes: 'SPACE MISSIONS',
    pausado: 'Paused',
    umDiaPorSegundo: '1 day/s',
    diasPorSegundo: '{n} days/s',
    hoje: 'Today',
    tituloSlider: 'Simulation speed — left goes back in time, right advances',
    chipEstrela: 'STAR',
    chipPlaneta: 'PLANET',
    chipPlanetaAnao: 'DWARF PLANET',
    chipLuaDe: 'MOON OF {nome}',
    chipLua: 'MOON',
    chipCinturao: 'BELT',
    chipAsteroide: 'ASTEROID',
    chipCometa: 'COMET',
    chipSonda: 'SPACE TELESCOPE',
    planetaAPartirDoSol: '{ordinal} planet from the Sun',
    luaDe: 'Moon of {nome}',
    curiosidades: 'Interesting facts',
    paraSentirEscala: 'To feel the scale',
    luas: 'Moons',
    saibaMais: 'Learn more (11+)',
    composicao: 'Composition:',
    temperatura: 'Temperature:',
    missoesExploratorias: 'Exploratory missions',
    eventosTitulo: 'Events',
    jaPassou: 'ALREADY HAPPENED',
    irParaData: 'Go to date',
    semEventos: 'No events available.',
    tipoEvento_eclipse: 'ECLIPSE',
    tipoEvento_oposicao: 'OPPOSITION',
    tipoEvento_conjuncao: 'CONJUNCTION',
    tipoEvento_chuva_meteoros: 'METEOR SHOWER',
    tipoEvento_cometa: 'COMET',
    tipoEvento_marco: 'MILESTONE',
    comparadorTitulo: 'Size Comparison',
    incluirSol: 'Include the Sun',
    paradaDe: 'STOP {n} OF {m}',
    anterior: '← Previous',
    proximo: 'Next →',
    concluir: 'Complete',
    sair: 'Exit',
    irParaLancamento: 'Go to launch',
    seguirNave: '🛰 Follow the spacecraft',
    toastDica: 'Drag to rotate · Scroll to zoom · Click on a celestial body to learn about it',
    credito: 'Textures: Solar System Scope (CC BY 4.0) · Data: NASA/JPL',
    seletorIdioma: 'Language',
    meses: [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ],
    mesesCurtos: [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ],
    proBadge: 'PRO',
    paywallTitulo: 'Explorer Pro',
    paywallSubtitulo: 'Unlock complete exploration',
    paywallBeneficio1: 'Full Space Quiz with medals and sky treasure hunts',
    paywallBeneficio2: 'All 10 space missions with real 3D trajectories',
    paywallBeneficio3: 'Time travel to eclipses and astronomical events',
    paywallBeneficio4: 'Your weight, age and jump on every planet',
    paywallPreco: 'US$ 2.99 · one-time purchase',
    paywallComprar: 'Unlock now',
    paywallComprando: 'Processing…',
    paywallRestaurar: 'Restore purchase',
    paywallSucesso: 'Unlocked! Enjoy your cosmic journey.',
    paywallErro: 'Could not complete. Please try again.',
    paywallRestaurado: 'Purchase restored!',
    paywallNadaRestaurar: 'No previous purchases found.',
    paywallLegal: 'Demo payment (mock) — no real charges are made in this version.',
    cadeadoTitulo: 'Pro feature — tap to unlock'
  },
  es: {
    htmlLang: 'es',
    tituloApp: 'Sistema Solar — Simulador Interactivo',
    titulo: 'SISTEMA SOLAR',
    subtitulo: 'Simulador interactivo',
    btnEventos: '✦ Eventos',
    btnTamanhos: '⚖ Tamaños',
    btnQuiz: '◈ Quiz',
    btnVoce: '◍ Tú en el Espacio',
    btnTour: '▶ Tour guiado',
    escalaDidatica: 'Didáctica',
    escalaReal: 'Real',
    btnOrbitas: 'Órbitas',
    btnRotulos: 'Etiquetas',
    btnVisaoGeral: '⌂ Vista general',
    explorar: 'Explorar',
    recolherMenu: 'Contraer menú',
    expandirMenu: 'Expandir menú',
    grupoEstrela: 'ESTRELLA',
    grupoPlanetas: 'PLANETAS',
    grupoAnoes: 'PLANETAS ENANOS',
    grupoCinturoes: 'CINTURONES',
    grupoAsteroides: 'ASTEROIDES',
    grupoCometas: 'COMETAS',
    grupoTelescopios: 'TELESCOPIOS ESPACIALES',
    grupoMissoes: 'MISIONES ESPACIALES',
    pausado: 'En pausa',
    umDiaPorSegundo: '1 día/s',
    diasPorSegundo: '{n} días/s',
    hoje: 'Hoy',
    tituloSlider: 'Velocidad de simulación — izquierda retrocede en el tiempo, derecha avanza',
    chipEstrela: 'ESTRELLA',
    chipPlaneta: 'PLANETA',
    chipPlanetaAnao: 'PLANETA ENANO',
    chipLuaDe: 'LUNA DE {nome}',
    chipLua: 'LUNA',
    chipCinturao: 'CINTURÓN',
    chipAsteroide: 'ASTEROIDE',
    chipCometa: 'COMETA',
    chipSonda: 'TELESCOPIO ESPACIAL',
    planetaAPartirDoSol: '{ordinal} planeta desde el Sol',
    luaDe: 'Luna de {nome}',
    curiosidades: 'Datos interesantes',
    paraSentirEscala: 'Para sentir la escala',
    luas: 'Lunas',
    saibaMais: 'Saber más (11+)',
    composicao: 'Composición:',
    temperatura: 'Temperatura:',
    missoesExploratorias: 'Misiones exploratorias',
    eventosTitulo: 'Eventos',
    jaPassou: 'YA PASÓ',
    irParaData: 'Ir a la fecha',
    semEventos: 'Ningún evento disponible.',
    tipoEvento_eclipse: 'ECLIPSE',
    tipoEvento_oposicao: 'OPOSICIÓN',
    tipoEvento_conjuncao: 'CONJUNCIÓN',
    tipoEvento_chuva_meteoros: 'LLUVIA DE METEOROS',
    tipoEvento_cometa: 'COMETA',
    tipoEvento_marco: 'HITO',
    comparadorTitulo: 'Comparador de Tamaños',
    incluirSol: 'Incluir el Sol',
    paradaDe: 'PARADA {n} DE {m}',
    anterior: '← Anterior',
    proximo: 'Siguiente →',
    concluir: 'Completar',
    sair: 'Salir',
    irParaLancamento: 'Ir al lanzamiento',
    seguirNave: '🛰 Seguir la nave',
    toastDica: 'Arrastra para rotar · Desplázate para ampliar · Haz clic en un cuerpo celeste para conocerlo',
    credito: 'Texturas: Solar System Scope (CC BY 4.0) · Datos: NASA/JPL',
    seletorIdioma: 'Idioma',
    meses: [
      'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
      'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'
    ],
    mesesCurtos: [
      'ene', 'feb', 'mar', 'abr', 'may', 'jun',
      'jul', 'ago', 'sep', 'oct', 'nov', 'dic'
    ],
    proBadge: 'PRO',
    paywallTitulo: 'Explorador Pro',
    paywallSubtitulo: 'Desbloquea la exploración completa',
    paywallBeneficio1: 'Quiz Espacial completo con medallas y búsqueda de astros',
    paywallBeneficio2: 'Las 10 misiones espaciales con trayectorias reales en 3D',
    paywallBeneficio3: 'Viaje en el tiempo a eclipses y eventos astronómicos',
    paywallBeneficio4: 'Tu peso, edad y salto en cada planeta',
    paywallPreco: 'US$ 2,99 · pago único',
    paywallComprar: 'Desbloquear ahora',
    paywallComprando: 'Procesando…',
    paywallRestaurar: 'Restaurar compra',
    paywallSucesso: '¡Desbloqueado! Disfruta tu viaje cósmico.',
    paywallErro: 'No se pudo completar. Intenta de nuevo.',
    paywallRestaurado: '¡Compra restaurada!',
    paywallNadaRestaurar: 'No se encontraron compras anteriores.',
    paywallLegal: 'Pago de demostración (mock) — no se realizan cargos reales en esta versión.',
    cadeadoTitulo: 'Función Pro — toca para desbloquear'
  }
};
