export const UI_TEXTOS = {
  pt: {
    htmlLang: 'pt-BR',
    tituloApp: 'Sistema Solar — Simulador Interativo',
    titulo: 'SISTEMA SOLAR',
    subtitulo: 'Simulador interativo',
    btnEventos: '✦ Eventos',
    btnTamanhos: '⚖ Tamanhos',
    btnQuiz: '◈ Quiz',
    btnVoce: '◍ Você no Espaço',
    btnTour: '▶ Tour guiado',
    grupoExperiencias: 'Experiências',
    grupoVisualizacao: 'Visualização',
    grupoUtilidades: 'Utilidades',
    escalaDidatica: 'Didática',
    escalaReal: 'Real',
    btnOrbitas: 'Órbitas',
    btnRotulos: 'Rótulos',
    btnVisaoGeral: '⌂ Visão geral',
    explorar: 'Explorar',
    recolherMenu: 'Recolher menu',
    expandirMenu: 'Expandir menu',
    verLuasDe: 'Ver luas de {nome}',
    ocultarLuasDe: 'Ocultar luas de {nome}',
    expandirGrupo: 'Expandir {nome}',
    recolherGrupo: 'Recolher {nome}',
    grupoEstrela: 'ESTRELA',
    grupoPlanetas: 'PLANETAS',
    grupoAnoes: 'PLANETAS-ANÕES',
    grupoCinturoes: 'CINTURÕES',
    grupoAsteroides: 'ASTEROIDES',
    grupoCometas: 'COMETAS',
    grupoTelescopios: 'TELESCÓPIOS ESPACIAIS',
    grupoMissoes: 'MISSÕES ESPACIAIS',
    pausado: 'Pausado',
    umDiaPorSegundo: '1 dia/s',
    umaHoraPorSegundo: '1 hora/s',
    diasPorSegundo: '{n} dias/s',
    hoje: 'Hoje',
    tituloSlider: 'Velocidade da simulação — esquerda volta no tempo, direita avança',
    chipEstrela: 'ESTRELA',
    chipPlaneta: 'PLANETA',
    chipPlanetaAnao: 'PLANETA-ANÃO',
    chipLuaDe: 'LUA DE {nome}',
    chipLua: 'LUA',
    chipCinturao: 'CINTURÃO',
    chipAsteroide: 'ASTEROIDE',
    chipCometa: 'COMETA',
    chipSonda: 'TELESCÓPIO ESPACIAL',
    planetaAPartirDoSol: '{ordinal} planeta a partir do Sol',
    luaDe: 'Lua de {nome}',
    curiosidades: 'Curiosidades',
    paraSentirEscala: 'Para sentir a escala',
    luas: 'Luas',
    saibaMais: 'Saiba mais (11+)',
    composicao: 'Composição:',
    temperatura: 'Temperatura:',
    missoesExploratorias: 'Missões exploratórias',
    eventosTitulo: 'Eventos',
    jaPassou: 'JÁ PASSOU',
    irParaData: 'Ir para a data',
    semEventos: 'Nenhum evento disponível.',
    tipoEvento_eclipse: 'ECLIPSE',
    tipoEvento_oposicao: 'OPOSIÇÃO',
    tipoEvento_conjuncao: 'CONJUNÇÃO',
    tipoEvento_chuva_meteoros: 'CHUVA DE METEOROS',
    tipoEvento_cometa: 'COMETA',
    tipoEvento_marco: 'MARCO',
    comparadorTitulo: 'Comparador de Tamanhos',
    incluirSol: 'Incluir o Sol',
    paradaDe: 'PARADA {n} DE {m}',
    anterior: '← Anterior',
    proximo: 'Próximo →',
    concluir: 'Concluir',
    sair: 'Sair',
    irParaLancamento: 'Ir para o lançamento',
    seguirNave: '🛰 Seguir a nave',
    toastDica: 'Arraste para girar · Role para dar zoom · Clique em um astro para conhecê-lo',
    credito: 'Texturas: Solar System Scope (CC BY 4.0), NASA/JPL/USGS, Askaniy Anpilogov et al. (CC BY-SA 3.0/4.0, Wikimedia) · Dados: NASA/JPL',
    seletorIdioma: 'Idioma',
    sondaOlhoTitulo: 'Mostrar/ocultar telescópio na cena',
    meses: [
      'janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho',
      'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'
    ],
    mesesCurtos: [
      'jan', 'fev', 'mar', 'abr', 'mai', 'jun',
      'jul', 'ago', 'set', 'out', 'nov', 'dez'
    ],
    proBadge: 'PRO',
    paywallTitulo: 'Explorador Pro',
    paywallSubtitulo: 'Desbloqueie a exploração completa',
    paywallBeneficio1: 'Quiz Espacial completo com medalhas e caça aos astros',
    paywallBeneficio2: 'Todas as 10 missões espaciais com trajetórias reais em 3D',
    paywallBeneficio3: 'Viagem no tempo até eclipses e eventos astronômicos',
    paywallBeneficio4: 'Seu peso, idade e salto em cada planeta',
    paywallPreco: 'R$ 12,90 · compra única',
    paywallReciprocidade: 'Os 43 astros, o tour guiado e a viagem no tempo já são seus, de graça. O Pro abre o resto.',
    paywallAncora: 'Pague uma vez, use para sempre — sem mensalidade.',
    paywallPerda: 'Sem o Pro, o Quiz completo, as 10 missões e os eventos astronômicos seguem trancados.',
    paywallComprar: 'Desbloquear agora',
    paywallComprando: 'Processando…',
    paywallRestaurar: 'Restaurar compra',
    paywallSucesso: 'Desbloqueado! Bom passeio pelo cosmos.',
    paywallErro: 'Não foi possível concluir. Tente novamente.',
    paywallRestaurado: 'Compra restaurada!',
    paywallNadaRestaurar: 'Nenhuma compra anterior encontrada.',
    paywallLegal: 'Pagamento de demonstração (mock) — nenhuma cobrança real é feita nesta versão.',
    cadeadoTitulo: 'Recurso Pro — toque para desbloquear',
    favLabel: 'Favoritar',
    favLabelAtivo: 'Favorito',
    favAdd: 'Adicionar aos favoritos',
    favRemover: 'Remover dos favoritos',
    grupoFavoritos: 'Meus favoritos',
    favVazioDica: 'Toque na ★ de um astro para guardá-lo aqui.',
    tutorialTitulo1: 'Bem-vindo ao Sistema Solar!',
    tutorialTexto1: 'Arraste para girar, role para dar zoom e clique em qualquer astro para conhecê-lo de perto.',
    tutorialTitulo2: 'Explore os astros',
    tutorialTexto2: 'Sol, planetas, luas, cometas e missões espaciais — clique em qualquer um da lista para viajar até ele.',
    tutorialTitulo3: 'Experiências',
    tutorialTexto3: 'Eventos astronômicos, comparador de tamanhos, quiz, seu peso em outros mundos e um tour guiado.',
    tutorialTitulo4: 'Modos de visualização',
    tutorialTexto4: 'Alterne entre a escala didática e a real, e mostre ou esconda órbitas e rótulos.',
    tutorialTitulo5: 'Viaje no tempo',
    tutorialTexto5: 'Acelere, pause ou escolha uma data — veja onde os planetas estavam no dia em que você nasceu!',
    tutorialTitulo6: 'Ganhe experiência',
    tutorialTexto6: 'Explorar astros, completar quizzes e missões dá XP. Suba de nível e vire um mestre do Sistema Solar!',
    tutorialProximo: 'Próximo',
    tutorialAnterior: 'Anterior',
    tutorialPular: 'Pular tutorial',
    tutorialFazerTour: '▶ Fazer o Tour guiado',
    tutorialExplorarSozinho: 'Explorar por conta própria',
    tutorialRever: 'Rever o tutorial'
  },
  en: {
    htmlLang: 'en',
    tituloApp: 'Solar System — Interactive Simulator',
    titulo: 'SOLAR SYSTEM',
    subtitulo: 'Interactive simulator',
    btnEventos: '✦ Events',
    btnTamanhos: '⚖ Sizes',
    btnQuiz: '◈ Quiz',
    btnVoce: '◍ You in Space',
    btnTour: '▶ Guided tour',
    grupoExperiencias: 'Experiences',
    grupoVisualizacao: 'View',
    grupoUtilidades: 'Utilities',
    escalaDidatica: 'Didactic',
    escalaReal: 'Real',
    btnOrbitas: 'Orbits',
    btnRotulos: 'Labels',
    btnVisaoGeral: '⌂ Overview',
    explorar: 'Explore',
    recolherMenu: 'Collapse menu',
    expandirMenu: 'Expand menu',
    verLuasDe: 'Show moons of {nome}',
    ocultarLuasDe: 'Hide moons of {nome}',
    expandirGrupo: 'Expand {nome}',
    recolherGrupo: 'Collapse {nome}',
    grupoEstrela: 'STAR',
    grupoPlanetas: 'PLANETS',
    grupoAnoes: 'DWARF PLANETS',
    grupoCinturoes: 'BELTS',
    grupoAsteroides: 'ASTEROIDS',
    grupoCometas: 'COMETS',
    grupoTelescopios: 'SPACE TELESCOPES',
    grupoMissoes: 'SPACE MISSIONS',
    pausado: 'Paused',
    umDiaPorSegundo: '1 day/s',
    umaHoraPorSegundo: '1 hour/s',
    diasPorSegundo: '{n} days/s',
    hoje: 'Today',
    tituloSlider: 'Simulation speed — left goes back in time, right advances',
    chipEstrela: 'STAR',
    chipPlaneta: 'PLANET',
    chipPlanetaAnao: 'DWARF PLANET',
    chipLuaDe: 'MOON OF {nome}',
    chipLua: 'MOON',
    chipCinturao: 'BELT',
    chipAsteroide: 'ASTEROID',
    chipCometa: 'COMET',
    chipSonda: 'SPACE TELESCOPE',
    planetaAPartirDoSol: '{ordinal} planet from the Sun',
    luaDe: 'Moon of {nome}',
    curiosidades: 'Interesting facts',
    paraSentirEscala: 'To feel the scale',
    luas: 'Moons',
    saibaMais: 'Learn more (11+)',
    composicao: 'Composition:',
    temperatura: 'Temperature:',
    missoesExploratorias: 'Exploratory missions',
    eventosTitulo: 'Events',
    jaPassou: 'ALREADY HAPPENED',
    irParaData: 'Go to date',
    semEventos: 'No events available.',
    tipoEvento_eclipse: 'ECLIPSE',
    tipoEvento_oposicao: 'OPPOSITION',
    tipoEvento_conjuncao: 'CONJUNCTION',
    tipoEvento_chuva_meteoros: 'METEOR SHOWER',
    tipoEvento_cometa: 'COMET',
    tipoEvento_marco: 'MILESTONE',
    comparadorTitulo: 'Size Comparison',
    incluirSol: 'Include the Sun',
    paradaDe: 'STOP {n} OF {m}',
    anterior: '← Previous',
    proximo: 'Next →',
    concluir: 'Complete',
    sair: 'Exit',
    irParaLancamento: 'Go to launch',
    seguirNave: '🛰 Follow the spacecraft',
    toastDica: 'Drag to rotate · Scroll to zoom · Click on a celestial body to learn about it',
    credito: 'Textures: Solar System Scope (CC BY 4.0), NASA/JPL/USGS, Askaniy Anpilogov et al. (CC BY-SA 3.0/4.0, Wikimedia) · Data: NASA/JPL',
    seletorIdioma: 'Language',
    sondaOlhoTitulo: 'Show/hide telescope in the scene',
    meses: [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ],
    mesesCurtos: [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
    ],
    proBadge: 'PRO',
    paywallTitulo: 'Explorer Pro',
    paywallSubtitulo: 'Unlock complete exploration',
    paywallBeneficio1: 'Full Space Quiz with medals and sky treasure hunts',
    paywallBeneficio2: 'All 10 space missions with real 3D trajectories',
    paywallBeneficio3: 'Time travel to eclipses and astronomical events',
    paywallBeneficio4: 'Your weight, age and jump on every planet',
    paywallPreco: 'US$ 2.99 · one-time purchase',
    paywallReciprocidade: 'The 43 worlds, the guided tour and time travel are already yours, free. Pro opens the rest.',
    paywallAncora: 'Pay once, keep it forever — no subscription.',
    paywallPerda: 'Without Pro, the full Quiz, all 10 missions and the astronomy events stay locked.',
    paywallComprar: 'Unlock now',
    paywallComprando: 'Processing…',
    paywallRestaurar: 'Restore purchase',
    paywallSucesso: 'Unlocked! Enjoy your cosmic journey.',
    paywallErro: 'Could not complete. Please try again.',
    paywallRestaurado: 'Purchase restored!',
    paywallNadaRestaurar: 'No previous purchases found.',
    paywallLegal: 'Demo payment (mock) — no real charges are made in this version.',
    cadeadoTitulo: 'Pro feature — tap to unlock',
    favLabel: 'Favorite',
    favLabelAtivo: 'Favorited',
    favAdd: 'Add to favorites',
    favRemover: 'Remove from favorites',
    grupoFavoritos: 'My favorites',
    favVazioDica: 'Tap the ★ on any object to keep it here.',
    tutorialTitulo1: 'Welcome to the Solar System!',
    tutorialTexto1: 'Drag to rotate, scroll to zoom, and click any celestial body to see it up close.',
    tutorialTitulo2: 'Explore the bodies',
    tutorialTexto2: 'Sun, planets, moons, comets and space missions — click any item on the list to travel to it.',
    tutorialTitulo3: 'Experiences',
    tutorialTexto3: 'Astronomical events, size comparator, quiz, your weight on other worlds and a guided tour.',
    tutorialTitulo4: 'View modes',
    tutorialTexto4: 'Switch between didactic and real scale, and show or hide orbits and labels.',
    tutorialTitulo5: 'Travel through time',
    tutorialTexto5: 'Speed up, pause or pick a date — see where the planets were on the day you were born!',
    tutorialTitulo6: 'Earn experience',
    tutorialTexto6: 'Exploring bodies, completing quizzes and missions earns XP. Level up and become a Solar System master!',
    tutorialProximo: 'Next',
    tutorialAnterior: 'Back',
    tutorialPular: 'Skip tutorial',
    tutorialFazerTour: '▶ Take the guided tour',
    tutorialExplorarSozinho: 'Explore on my own',
    tutorialRever: 'Replay tutorial'
  },
  es: {
    htmlLang: 'es',
    tituloApp: 'Sistema Solar — Simulador Interactivo',
    titulo: 'SISTEMA SOLAR',
    subtitulo: 'Simulador interactivo',
    btnEventos: '✦ Eventos',
    btnTamanhos: '⚖ Tamaños',
    btnQuiz: '◈ Quiz',
    btnVoce: '◍ Tú en el Espacio',
    btnTour: '▶ Tour guiado',
    grupoExperiencias: 'Experiencias',
    grupoVisualizacao: 'Visualización',
    grupoUtilidades: 'Utilidades',
    escalaDidatica: 'Didáctica',
    escalaReal: 'Real',
    btnOrbitas: 'Órbitas',
    btnRotulos: 'Etiquetas',
    btnVisaoGeral: '⌂ Vista general',
    explorar: 'Explorar',
    recolherMenu: 'Contraer menú',
    expandirMenu: 'Expandir menú',
    verLuasDe: 'Ver lunas de {nome}',
    ocultarLuasDe: 'Ocultar lunas de {nome}',
    expandirGrupo: 'Expandir {nome}',
    recolherGrupo: 'Contraer {nome}',
    grupoEstrela: 'ESTRELLA',
    grupoPlanetas: 'PLANETAS',
    grupoAnoes: 'PLANETAS ENANOS',
    grupoCinturoes: 'CINTURONES',
    grupoAsteroides: 'ASTEROIDES',
    grupoCometas: 'COMETAS',
    grupoTelescopios: 'TELESCOPIOS ESPACIALES',
    grupoMissoes: 'MISIONES ESPACIALES',
    pausado: 'En pausa',
    umDiaPorSegundo: '1 día/s',
    umaHoraPorSegundo: '1 hora/s',
    diasPorSegundo: '{n} días/s',
    hoje: 'Hoy',
    tituloSlider: 'Velocidad de simulación — izquierda retrocede en el tiempo, derecha avanza',
    chipEstrela: 'ESTRELLA',
    chipPlaneta: 'PLANETA',
    chipPlanetaAnao: 'PLANETA ENANO',
    chipLuaDe: 'LUNA DE {nome}',
    chipLua: 'LUNA',
    chipCinturao: 'CINTURÓN',
    chipAsteroide: 'ASTEROIDE',
    chipCometa: 'COMETA',
    chipSonda: 'TELESCOPIO ESPACIAL',
    planetaAPartirDoSol: '{ordinal} planeta desde el Sol',
    luaDe: 'Luna de {nome}',
    curiosidades: 'Datos interesantes',
    paraSentirEscala: 'Para sentir la escala',
    luas: 'Lunas',
    saibaMais: 'Saber más (11+)',
    composicao: 'Composición:',
    temperatura: 'Temperatura:',
    missoesExploratorias: 'Misiones exploratorias',
    eventosTitulo: 'Eventos',
    jaPassou: 'YA PASÓ',
    irParaData: 'Ir a la fecha',
    semEventos: 'Ningún evento disponible.',
    tipoEvento_eclipse: 'ECLIPSE',
    tipoEvento_oposicao: 'OPOSICIÓN',
    tipoEvento_conjuncao: 'CONJUNCIÓN',
    tipoEvento_chuva_meteoros: 'LLUVIA DE METEOROS',
    tipoEvento_cometa: 'COMETA',
    tipoEvento_marco: 'HITO',
    comparadorTitulo: 'Comparador de Tamaños',
    incluirSol: 'Incluir el Sol',
    paradaDe: 'PARADA {n} DE {m}',
    anterior: '← Anterior',
    proximo: 'Siguiente →',
    concluir: 'Completar',
    sair: 'Salir',
    irParaLancamento: 'Ir al lanzamiento',
    seguirNave: '🛰 Seguir la nave',
    toastDica: 'Arrastra para rotar · Desplázate para ampliar · Haz clic en un cuerpo celeste para conocerlo',
    credito: 'Texturas: Solar System Scope (CC BY 4.0), NASA/JPL/USGS, Askaniy Anpilogov et al. (CC BY-SA 3.0/4.0, Wikimedia) · Datos: NASA/JPL',
    seletorIdioma: 'Idioma',
    sondaOlhoTitulo: 'Mostrar/ocultar telescopio en la escena',
    meses: [
      'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
      'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'
    ],
    mesesCurtos: [
      'ene', 'feb', 'mar', 'abr', 'may', 'jun',
      'jul', 'ago', 'sep', 'oct', 'nov', 'dic'
    ],
    proBadge: 'PRO',
    paywallTitulo: 'Explorador Pro',
    paywallSubtitulo: 'Desbloquea la exploración completa',
    paywallBeneficio1: 'Quiz Espacial completo con medallas y búsqueda de astros',
    paywallBeneficio2: 'Las 10 misiones espaciales con trayectorias reales en 3D',
    paywallBeneficio3: 'Viaje en el tiempo a eclipses y eventos astronómicos',
    paywallBeneficio4: 'Tu peso, edad y salto en cada planeta',
    paywallPreco: 'US$ 2,99 · pago único',
    paywallReciprocidade: 'Los 43 astros, el tour guiado y el viaje en el tiempo ya son tuyos, gratis. Pro abre el resto.',
    paywallAncora: 'Paga una vez, para siempre — sin suscripción.',
    paywallPerda: 'Sin Pro, el Quiz completo, las 10 misiones y los eventos astronómicos siguen bloqueados.',
    paywallComprar: 'Desbloquear ahora',
    paywallComprando: 'Procesando…',
    paywallRestaurar: 'Restaurar compra',
    paywallSucesso: '¡Desbloqueado! Disfruta tu viaje cósmico.',
    paywallErro: 'No se pudo completar. Intenta de nuevo.',
    paywallRestaurado: '¡Compra restaurada!',
    paywallNadaRestaurar: 'No se encontraron compras anteriores.',
    paywallLegal: 'Pago de demostración (mock) — no se realizan cargos reales en esta versión.',
    cadeadoTitulo: 'Función Pro — toca para desbloquear',
    favLabel: 'Favorito',
    favLabelAtivo: 'Guardado',
    favAdd: 'Añadir a favoritos',
    favRemover: 'Quitar de favoritos',
    grupoFavoritos: 'Mis favoritos',
    favVazioDica: 'Toca la ★ de un astro para guardarlo aquí.',
    tutorialTitulo1: '¡Bienvenido al Sistema Solar!',
    tutorialTexto1: 'Arrastra para girar, desplázate para hacer zoom y haz clic en cualquier astro para conocerlo de cerca.',
    tutorialTitulo2: 'Explora los astros',
    tutorialTexto2: 'Sol, planetas, lunas, cometas y misiones espaciales: haz clic en cualquiera de la lista para viajar hasta él.',
    tutorialTitulo3: 'Experiencias',
    tutorialTexto3: 'Eventos astronómicos, comparador de tamaños, quiz, tu peso en otros mundos y un tour guiado.',
    tutorialTitulo4: 'Modos de visualización',
    tutorialTexto4: 'Alterna entre la escala didáctica y la real, y muestra u oculta órbitas y rótulos.',
    tutorialTitulo5: 'Viaja en el tiempo',
    tutorialTexto5: 'Acelera, pausa o elige una fecha: ¡mira dónde estaban los planetas el día que naciste!',
    tutorialTitulo6: 'Gana experiencia',
    tutorialTexto6: 'Explorar astros, completar quizzes y misiones da XP. ¡Sube de nivel y conviértete en un maestro del Sistema Solar!',
    tutorialProximo: 'Siguiente',
    tutorialAnterior: 'Anterior',
    tutorialPular: 'Saltar tutorial',
    tutorialFazerTour: '▶ Hacer el tour guiado',
    tutorialExplorarSozinho: 'Explorar por mi cuenta',
    tutorialRever: 'Volver a ver el tutorial'
  }
};
