// Dimensões de desenho aproximadas; intervalos de montagem em unidades didáticas.
export const PARTES = [
 {id:'sic',nome:'Primeiro estágio · S-IC',base:0,altura:42,raio:5,funcao:'Tirar o foguete da plataforma e atravessar a parte mais densa da atmosfera.',detalhes:'Cinco motores F-1 queimavam querosene RP-1 e oxigênio líquido. Os quatro motores externos ajudavam a orientar o veículo.',destino:'Separava-se após consumir seus propelentes e caía no oceano.'},
 {id:'inter1',nome:'Interestágio S-IC / S-II',base:42,altura:5,raio:5,funcao:'Conectar o primeiro e o segundo estágios e transmitir esforços durante a subida.',detalhes:'A estrutura envolvia a região dos motores do S-II. A separação liberava o estágio seguinte para continuar a aceleração.',destino:'Era descartado durante a sequência de separação dos estágios inferiores.'},
 {id:'sii',nome:'Segundo estágio · S-II',base:47,altura:24,raio:5,funcao:'Continuar a aceleração depois da separação do primeiro estágio.',detalhes:'Cinco motores J-2 utilizavam hidrogênio líquido e oxigênio líquido. Os tanques criogênicos exigiam isolamento térmico.',destino:'Era descartado antes de o terceiro estágio completar a inserção orbital.'},
 {id:'inter2',nome:'Interestágio S-II / S-IVB',base:71,altura:5,raio:5,funcao:'Fazer a transição entre o grande diâmetro do S-II e o S-IVB mais estreito.',detalhes:'A seção cônica protegia a região do motor do terceiro estágio e fazia parte da estrutura de separação.',destino:'Permanecia com o estágio inferior quando o S-IVB se separava.'},
 {id:'sivb',nome:'Terceiro estágio · S-IVB',base:76,altura:17,raio:3.3,funcao:'Completar a entrada em órbita terrestre e impulsionar a nave em direção à Lua.',detalhes:'Seu único motor J-2 podia ser religado. Na Apollo 11, uma segunda queima produziu a injeção translunar.',destino:'Após a extração do módulo lunar, separava-se do conjunto tripulado.'},
 {id:'iu',nome:'Unidade de instrumentos',base:93,altura:1,raio:3.3,funcao:'Orientar e controlar o foguete durante a ascensão.',detalhes:'Este anel alojava sistemas de navegação, computador de voo, telemetria e equipamentos eletrônicos. Não era um compartimento de tripulação.',destino:'Acompanhava o terceiro estágio.'},
 {id:'sla',nome:'Adaptador do módulo lunar',base:94,altura:9,raio:3.3,funcao:'Sustentar a nave Apollo e abrigar o módulo lunar durante o lançamento.',detalhes:'Quatro painéis protegiam o módulo lunar. Depois da injeção translunar, a abertura do adaptador permitia a manobra de acoplagem e extração.',destino:'Seus painéis eram descartados. A vista explodida os afasta para revelar o módulo lunar.'},
 {id:'lm',nome:'Módulo lunar · Eagle',base:94.5,altura:7,raio:2.5,funcao:'Levar dois astronautas da órbita lunar à superfície e trazê-los de volta à órbita.',detalhes:'O conjunto possui estágio de descida com trem de pouso e estágio de subida com cabine, motor e ponto de acoplagem. Aqui permanece inteiro, com as pernas recolhidas na montagem e abertas para inspeção.',destino:'O estágio de descida ficava na Lua. O de subida voltava à órbita para reencontrar o módulo de comando.'},
 {id:'sm',nome:'Módulo de serviço',base:103,altura:7,raio:2,funcao:'Fornecer propulsão, energia elétrica e recursos de suporte à vida.',detalhes:'Incluía o motor principal de serviço, tanques, células de combustível e pequenos propulsores de controle de atitude.',destino:'Separava-se da cápsula antes da reentrada; não retornava intacto.'},
 {id:'cm',nome:'Módulo de comando · Columbia',base:110,altura:3.5,raio:2,funcao:'Alojar os três astronautas e protegê-los na reentrada na atmosfera.',detalhes:'A cápsula cônica continha controles, assentos, escotilha e escudo térmico na base. Paraquedas reduziam a velocidade antes da amerissagem.',destino:'Era a única parte do conjunto tripulado que retornava intacta à Terra.'},
 {id:'les',nome:'Torre de escape',base:113.5,altura:10,raio:.65,funcao:'Afastar rapidamente a cápsula de comando em caso de emergência no início do voo.',detalhes:'Um foguete de combustível sólido, montado numa torre de treliça, podia puxar a cápsula para longe do lançador. A cobertura protegia o módulo de comando.',destino:'Era descartada quando deixava de ser necessária. Não seguia até a Lua.'}
];

export const FONTES = {
 kit: {nome:'NASA · Apollo 11 Press Kit (1969)',url:'https://www.nasa.gov/wp-content/uploads/static/apollo50th/pdf/A11_PressKit.pdf'},
 missao: {nome:'NASA · A missão Apollo 11',url:'https://www.nasa.gov/missions/apollo/apollo-11/apollo-11-mission-overview/'},
 foguete: {nome:'NASA · Conheça o Saturno V',url:'https://www.nasa.gov/learning-resources/for-kids-and-students/what-was-the-saturn-v-grades-5-8/'},
 apollo: {nome:'NASA · O programa Apollo',url:'https://www.nasa.gov/the-apollo-program/'}
};
const APRENDER = {
 sic: {curto:'1º estágio',apelido:'O gigante que dá a partida',crianca:'Cinco motores enormes levantam o foguete do chão. Eles trabalham juntos para vencer a gravidade e começar a viagem.',analogia:'É como a primeira equipe de uma corrida de revezamento: dá a largada e passa a tarefa adiante.',pergunta:'Gire a peça e olhe por baixo. Consegue encontrar os cinco motores?',numeros:[['Motores','5 × F-1'],['Altura real','≈ 42,1 m'],['Combustível','Querosene RP-1 + oxigênio líquido']],fontes:['foguete','kit']},
 inter1: {curto:'Anel de ligação',apelido:'A ponte entre dois gigantes',crianca:'Este anel une os dois primeiros estágios. Ele também envolve os motores do segundo estágio enquanto o foguete está montado.',analogia:'Pense em uma peça de encaixe que segura dois blocos grandes juntos. Ela não é um tanque de combustível.',pergunta:'Ao separar, você consegue ver que este anel é oco?',numeros:[['Tipo','Estrutura de ligação'],['Tripulantes','Nenhum']],fontes:['kit']},
 sii: {curto:'2º estágio',apelido:'A equipe que continua a subida',crianca:'Quando a primeira parte termina seu trabalho, estes cinco motores continuam acelerando a nave. O foguete fica mais leve ao deixar para trás as peças usadas.',analogia:'É como tirar uma mochila vazia para correr com menos peso.',pergunta:'Os motores daqui são do mesmo tamanho que os do primeiro estágio?',numeros:[['Motores','5 × J-2'],['Altura real','≈ 24,8 m'],['Combustível','Hidrogênio + oxigênio líquidos']],fontes:['foguete','kit']},
 inter2: {curto:'Anel de transição',apelido:'Do largo para o estreito',crianca:'Esta ligação afunilada conecta a parte larga do foguete à parte mais estreita que fica acima dela.',analogia:'Lembra um adaptador entre dois tubos de tamanhos diferentes, mas aqui sua função é estrutural.',pergunta:'Qual das duas aberturas é maior?',numeros:[['Forma','Tronco de cone'],['Função','União e proteção do motor']],fontes:['kit']},
 sivb: {curto:'3º estágio',apelido:'O último empurrão rumo à Lua',crianca:'Seu motor primeiro ajuda a nave a entrar em órbita da Terra. Depois ele liga de novo para colocar a nave no caminho da Lua.',analogia:'É um motor que guarda combustível para uma segunda tarefa.',pergunta:'Aqui há só um motor. Por que ele não precisa levantar todo o foguete da plataforma?',numeros:[['Motor','1 × J-2'],['Altura real','≈ 17,8 m'],['Na Apollo 11','Duas queimas principais']],fontes:['foguete','missao','kit']},
 iu: {curto:'Instrumentos',apelido:'O navegador do foguete',crianca:'Dentro deste anel ficam aparelhos que ajudam o foguete a saber para onde está indo e como corrigir o caminho. Não há astronautas aqui.',analogia:'É uma central de navegação automática, com sensores e computador.',pergunta:'Você imaginava que um anel tão pequeno podia ajudar a guiar um foguete tão grande?',numeros:[['Formato','Anel de equipamentos'],['Altura real','≈ 0,91 m']],fontes:['kit']},
 sla: {curto:'Proteção do Eagle',apelido:'A garagem do módulo lunar',crianca:'Quatro painéis guardam o Eagle durante a subida. Eles são retirados no espaço para a nave conseguir buscar o módulo lunar.',analogia:'É como uma embalagem protetora que também ajuda a sustentar a nave acima dela.',pergunta:'Separe as peças. Qual nave estava escondida dentro desta proteção?',numeros:[['Painéis','4'],['Sigla','SLA · adaptador do módulo lunar']],fontes:['missao','kit']},
 lm: {curto:'Módulo lunar',apelido:'Eagle: o visitante da Lua',crianca:'Esta é a nave que levou Neil Armstrong e Buzz Aldrin ao chão da Lua. Michael Collins ficou em órbita, no Columbia.',analogia:'A base dourada serve para pousar. A cabine de cima decola da Lua e reencontra a outra nave.',pergunta:'Encontre as pernas e a escada. Qual parte ficou na Lua?',numeros:[['Tripulantes','2'],['Partes principais','Descida + subida'],['Pouso','20 de julho de 1969']],fontes:['apollo','missao']},
 sm: {curto:'Módulo de serviço',apelido:'A mochila de recursos da nave',crianca:'Leva o motor principal da nave Apollo e recursos para a viagem, como oxigênio e equipamentos que produzem eletricidade.',analogia:'É a mochila de uma longa aventura, com energia e suprimentos para a cápsula.',pergunta:'Encontre o motor grande e os pequenos propulsores nas laterais.',numeros:[['Tripulantes','Nenhum nesta seção'],['Conjunto com a cápsula','CSM']],fontes:['apollo','kit']},
 cm: {curto:'Cápsula Columbia',apelido:'A casa que volta para a Terra',crianca:'Os três astronautas viajam nesta cápsula na partida e na volta. Seu escudo térmico protege a tripulação do calor intenso ao entrar na atmosfera.',analogia:'É uma pequena casa com uma base protetora. Paraquedas ajudam a pousar no oceano.',pergunta:'Gire a cápsula. Você consegue ver o escudo escuro na base?',numeros:[['Tripulantes','3'],['Nome','Columbia'],['Retorno','24 de julho de 1969']],fontes:['apollo','missao','kit']},
 les: {curto:'Torre de escape',apelido:'O resgate de emergência',crianca:'Se houvesse um problema grave no começo da subida, este foguete pequeno poderia puxar a cápsula para longe do foguete grande.',analogia:'É um sistema de resgate preparado antes de sair, mesmo que não precise ser usado.',pergunta:'Por que ele fica acima da cápsula, em vez de abaixo dela?',numeros:[['Propelente','Sólido'],['Uso','Emergência no início do voo']],fontes:['kit']}
};
for (const p of PARTES) Object.assign(p, APRENDER[p.id]);
PARTES.find(p=>p.id==='sivb').destino='Na Apollo 11, o terceiro estágio seguiu para uma órbita ao redor do Sol depois que o Eagle foi retirado.';
PARTES.find(p=>p.id==='sla').detalhes='Após a injeção translunar, o conjunto de comando e serviço se afastava, girava e acoplava ao Eagle. Os painéis do SLA eram ejetados; não eram portas reutilizáveis. A abertura no hangar é uma ilustração para estudar as peças.';
PARTES.find(p=>p.id==='lm').detalhes='O estágio de descida levava motor, propelentes e trem de pouso. O estágio de subida continha cabine pressurizada e seu próprio motor. O Eagle não tinha escudo para reentrar na atmosfera terrestre. A aparência externa é uma aproximação didática.';
PARTES.find(p=>p.id==='sm').detalhes='O motor SPS fazia grandes mudanças de velocidade. Pequenos propulsores RCS controlavam a orientação. Células de combustível produziam eletricidade com hidrogênio e oxigênio; radiadores ajudavam a eliminar calor.';
// Estações de montagem ilustrativas: mantêm o envelope ≈ 110,6 unidades.
// Os comprimentos reais de estágio incluem regiões sobrepostas aos interestágios.
const montagem={sic:[0,42],inter1:[42,5],sii:[44,22],inter2:[66,5],sivb:[68.5,15.5],iu:[84,1],sla:[85,9],lm:[85.5,7],sm:[92,7],cm:[99,3.5],les:[102.5,8.1]};
for(const p of PARTES) { [p.base,p.altura]=montagem[p.id]; }
export function posicaoParte(p,index,explodido){
 return {x:p.id==='lm'&&explodido?16:0,y:p.base+(explodido?(p.id==='lm'?6:index)*7:0),z:0};
}
